### ISSUE TITLE
Automate using GitHub Actions

### ISSUE THREAD

**Issue by hello-smile6** [micahlt/sbarchive#25]
This needs automated.

**Comment by hello-smile6** [comment]
> Could you elaborate? What needs automation?

All of this. You could have a script that will run for as long as GitHub Actions allows and will publish results to a release, effectively offloading everything onto GitHub's servers.

**Comment by hello-smile6** [comment]
> Possibly. @micahlt would have to look into it.

[Replit](https://replit.com/) could also have several servers sending data to participating users' devices using [Bugout](https://chr15m.github.io/bugout) and [WebTorrent](https://webtorrent.io/)...

**Comment by micahlt** [comment]
@hello-smile6 That's not what GitHub Actions is meant for, and it most likely breaks the Terms of Service.  Manually doing it isn't as fun, but it ensures that everything is working correctly and that people are not abusing computing power.
