### ISSUE TITLE
The PR is unmerged!

### ISSUE THREAD

**Issue by hello-smile6** [micahlt/sbarchive#29]
If the release happens on time, the PR will be unmerged!
https://github.com/LLK/scratch-www/ #6828
(Avoiding getting a mention on the PR)

**Comment by hello-smile6** [comment]
> So we should be good until the next release then?

If they don't get it fixed before they release, it should be good until then, but you never know.

**Comment by hello-smile6** [comment]
@MagentaSuperNova Could you create a mirror of this repo on my [Gitea instance](https://gitea.9pfs.repl.co/user/oauth2/github), by chance? I'd like to have a mirror to use.

**Comment by micahlt** [comment]
How often are releases?

**Comment by hello-smile6** [comment]
> How often are releases?

Not sure, maybe check when similar PRs are.

**Comment by hello-smile6** [comment]
> > How often are releases?
> 
> Seems to be every 7 days or so by looking at the actions page.

So there's at least 1 week. Maybe people need to look for bugs more in order to overwhelm everyone.

**Comment by micahlt** [comment]
@hello-smile6 Thanks for the info!  Closing this for now, as there's no action required on this issue.
