### ISSUE TITLE
Save only project JSON file

### ISSUE THREAD

**Issue by Chiroyce1** [micahlt/sbarchive#3]
Isn't it better to save just the JSON files? this way less space is taken up and I'm pretty sure assets will remain publicly accessible. 

PR [#8269](https://github.com/LLK/scratch-gui/pull/8269) in scratch-gui adds the token to the project URL, but not the asset URL, and it's already been merged. Line [#62](https://github.com/LLK/scratch-gui/blob/794098eb939f0d2296d5864e7e1dd1dd13c36215/src/lib/storage.js#L62) is the URL for the asset, and as you can see it doesn't contain an extra query parameter, unlike line [#44](https://github.com/LLK/scratch-gui/blob/794098eb939f0d2296d5864e7e1dd1dd13c36215/src/lib/storage.js#L44), whose URL also contains the token as a query param. Since it has already been merged, and PR [#6773](https://github.com/LLK/scratch-www/pull/6773/) doesn't modify the assets url, it's pretty safe to assume that assets will remain public. 

The file modified in both the PRs that actually bring about this change is `src/lib/storage.js`

**Comment by micahlt** [comment]
Thanks for your concert @Chiroyce1!

> Oh yeah! @micahlt isn't it better to save just the JSON files? this way less space is taken up and I'm pretty sure assets will remain publicly accessible.

I'm open to that - what makes you think that assets will remain public?

**Comment by Chiroyce1** [comment]
> I'm open to that - what makes you think that assets will remain public?

PR [#8269](https://github.com/LLK/scratch-gui/pull/8269) in scratch-gui adds the token to the project URL, but not the asset URL, and it's already been merged. Line [#62](https://github.com/LLK/scratch-gui/blob/794098eb939f0d2296d5864e7e1dd1dd13c36215/src/lib/storage.js#L62) is the URL for the asset, and as you can see it doesn't contain an extra query parameter, unlike line [#44](https://github.com/LLK/scratch-gui/blob/794098eb939f0d2296d5864e7e1dd1dd13c36215/src/lib/storage.js#L44), whose URL also contains the token as a query param. Since it has already been merged, and PR [#6773](https://github.com/LLK/scratch-www/pull/6773/) doesn't modify the assets url, it's pretty safe to assume that assets will remain public. 

The file modified in both the PRs that actually bring about this change is `src/lib/storage.js`

**Comment by Chiroyce1** [comment]
@micahlt looks like the code as of now saves all projects as JSON only (is this a mistake?) and now if someone clones and runs it (like I did) blank files are getting mixed/overwritten with JSON files in `projects/` - so the file extension in line [#28](https://github.com/micahlt/sbarchive/blob/f19670926f24e0cb9e0dc3e74ea130236a684040/index.js#L28) should be changed to `.json` instead of `.sb3`.

**Comment by Chiroyce1** [comment]
> Once we get to `.sb2` & `.sb3` projects we would only be downloading the JSON anyway as the assets are accessed at a different endpoint. See #8

Right, that makes sense. But currently almost all the files have .sb3 instead of just .sb - we need to make sure to keep the file extensions straight so that we can modify this data later on properly.

**Comment by Chiroyce1** [comment]
I indexed the latest 10,000 projects over here - (from id 692629836 to 692639836) 
https://scratch-archive.chiroyce.repl.co/index

To access a project's JSON file, the URL is https://scratch-archive.chiroyce.repl.co/project/{id}
The response will be JSON of
```json
{
    "project": "JSON object of Project's JSON file",
    "info": "JSON object of what the API returned for this project"
}
```
I unfortunately don't have git locally right now so I am unable to PR here, so if you can, please do so.

**Comment by Chiroyce1** [comment]
> I never thought of using replit. A good idea!

Yep, but unfortunately space is a big issue (if you don't have hacker plan) and 10,000 projects itself consumes around ~50% of all the repl's storage -  I am currently working on one that is indexing 20,000 projects and I guess that's the limit.

**Comment by Chiroyce1** [comment]
> @Chiroyce1 something's wrong with your repl. I keep getting `500` errors.

Can I get the URL you are sending a request to? Make sure not to add `.json` to the end, and also make sure the ID you are requesting is there in the array you get from `/index`

Also @micahlt @MagentaSuperNova - see [this](https://scratch.mit.edu/users/DatOneLefty/#comments-179169144)!!

<img width="1105" alt="image" src="https://user-images.githubusercontent.com/97374054/169215222-d8915d90-4b6e-4782-a772-257c5ee2c89d.png">
So Lefty (the hoister and creator of ScratchDB) possibly has all the files!!

**Comment by Chiroyce1** [comment]
> Also, all of the projects that we have archived so far are just the project files, no metadata.

API data? I have that.. but most projects are unshared :/
