### ISSUE TITLE
might take up too much space

### ISSUE THREAD

**Issue by Oren-Lindsey** [micahlt/sbarchive#4]
[![discord message](https://user-images.githubusercontent.com/67929847/169047687-4c6bd572-8742-4588-a530-67ca1b6ceedc.png)](https://discord.com/channels/558340604627648539/604602687820005406/976326709324435458)

[![discord message](https://user-images.githubusercontent.com/67929847/169047892-e550b756-22d6-4934-a799-e2d241eef5ad.png)](https://discord.com/channels/558340604627648539/604602687820005406/976312697983471646)

**Comment by micahlt** [comment]
I wasn't aware that there have already been projects archived!  @Oren-Lindsey, would you be willing to speak to those users and ask if they'd be willing to help distribute those projects in a way that anyone can access?

**Comment by micahlt** [comment]
> I plan to upload them to The Internet Archive, and possibly other online archiving services (if you have suggestions).

The Internet Archive is a great idea!  That's a much better plan than cloud storage controlled by a single person.

**Comment by ninjamar** [comment]
Would ~500gb of storage help?

**Comment by micahlt** [comment]
We're moving these files to the Internet Archive.  Thanks for your contribution!
