### ISSUE TITLE
Save projects in the correct file format (.sb vs .sb3)

### ISSUE THREAD

**Issue by crs100** [micahlt/sbarchive#8]
There is something incredibly important to note- projects leading up to ID 3.8 million or so should be saved as .sb files, not .sb3.

Additionally:
Projects made in Scratch 1 will return a large binary file with a "ScratchV0" header (the file is the entire project.)
Projects made in Scratch 2 and 3 will return a .JSON file (the .json, only, not any of the project's assets.)

Some sort of routine should be written to determine if the file is a Scratch 1 project or a Scratch 2/3 project.

**Comment by crs100** [comment]
> A few questions...
> 
> **1.** I assume `.sb2` & `.sb3` files can store assets because I can save projects to my computer and all of the assets are there. So are the assets stored separately only on the server-side?
> 
> **2.** Does anyone know the specific ID where projects switch to `.sb2`? The same for `.sb3`?
> 
> **3.** Is there anyway for us to download the assets for a `.sb2` project and combine the assets into the JSON file? Having the JSON and assets separate would cause quite some complexity when organizing and compressing the files.
> 
> On a side-note, we aren't even close to archiving half a million projects, let alone 3.8 million, and the Scratch Team could block access to them at any time now, so I wouldn't worry about this until it becomes an issue.

1. They are stored in a separate place, yes (cdn.assets.scratch.mit.edu)

2. There is no "specific ID" where projects switch to .sb2. When Scratch 2.0 was released, the project IDs jumped from 3.8 million to 10 million, however, well after 2.0's release there were still users uploading projects in Scratch 1.4 because they were resistant to make the switch to 2.0. For example, project ID 12000000 could be an sb2, and 12000001 could be an .sb. 

3. You can't "combine" the assets into the JSON file, but rather pair them with the JSON file and put them into a .zip, thus completing the .sb2 file. And yes, there is. [a](https://github.com/forkphorus/sb-downloader/l)

**Comment by micahlt** [comment]
@MagentaSuperNova that's what the sb3.micahlindley.com endpoint is intended to do.  However, it appears that the code is faulty.

**Comment by micahlt** [comment]
Yes!  Here: https://github.com/cdchushig/getsb3

**Comment by micahlt** [comment]
There's very little documentation though, besides running and building with Docker (which I didn't do with my deployment).

**Comment by micahlt** [comment]
If you can get the getsb3 server working correctly, that would vastly improve the downloads process.

**Comment by micahlt** [comment]
After some investigating, it appears that the API was being ratelimited.  I'm able to use getsb3 successfully when I use a 500ms delay between requests.

**Comment by micahlt** [comment]
In 99% of cases I've encountered, Scratch and Turbowarp don't care about the extension.  They're smart enough to parse the project no matter what.

**Comment by micahlt** [comment]
Yeah, I'm writing out the code now.

**Comment by crs100** [comment]
> In 99% of cases I've encountered, Scratch and Turbowarp don't care about the extension. They're smart enough to parse the project no matter what.

The correct extension is necessary when opening the project natively in Scratch 1.4. And yes, you could always just manually rename the files to have the correct extension, but having the process be automated would be a lot more convenient.

**Comment by crs100** [comment]
> > > In 99% of cases I've encountered, Scratch and Turbowarp don't care about the extension. They're smart enough to parse the project no matter what.
> > 
> > 
> > The correct extension is necessary when opening the project natively in Scratch 1.4. And yes, you could always just manually rename the files to have the correct extension, but having the process be automated would be a lot more convenient.
> 
> Due to the amount of time we have to download the files, this is something we could work on after (see [here](https://github.com/micahlt/sbarchive/issues/3#issuecomment-1131184826))
Probably a good point.

**Comment by micahlt** [comment]
@MagentaSuperNova changes pushed - try now
